# Generated by Django 3.0.4 on 2020-03-23 06:26

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('alertas', '0003_auto_20200322_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggression',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
